const slots = [
    {id:1 , time:"9:00 AM", available: true, disabled:false },
    {id:2 , time:"9:20 AM", available: true, disabled:false },
    {id:3 , time:"9:40 AM", available: true, disabled:false },
    {id:5 , time:"10:00 AM", available: true, disabled:false },
    {id:6 , time:"10:20 AM", available: true, disabled:false },
    {id:7 , time:"10:40 AM", available: true, disabled:false },
    {id:8 , time:"11:00 AM", available: true, disabled:false },
    {id:9 , time:"11:20 AM", available: true, disabled:false },
    {id:10 , time:"11:40 AM", available: true, disabled:false },
    {id:11 , time:"12:00 PM", available: true, disabled:false },
    {id:12 , time:"1:00 PM", available: true, disabled:false },
    {id:13 , time:"1:20 PM", available: true, disabled:false },
    {id:14 , time:"1:40 PM", available: true, disabled:false },
    {id:15 , time:"2:00 PM", available: true, disabled:false },
    {id:16 , time:"2:20 PM", available: true, disabled:false },
    {id:17 , time:"2:40 PM", available: true, disabled:false },
    {id:18 , time:"3:00 PM", available: true, disabled:false },
    {id:19 , time:"3:20 PM", available: true, disabled:false },
    {id:20 , time:"3:40 PM", available: true, disabled:false },
    {id:21 , time:"4:00 PM", available: true, disabled:false },
    {id:22 , time:"4:20 PM", available: true, disabled:false },
    {id:23 , time:"4:40 PM", available: true, disabled:false },
    {id:24 , time:"5:00 PM", available: true, disabled:false },
];
module.exports = slots;

